FROM node:22.14-alpine AS builder
WORKDIR /app

# Build arguments for Next.js environment variables
ARG NEXT_PUBLIC_AWS_PROJECT_REGION
ARG NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT
ARG NEXT_PUBLIC_AWS_APPSYNC_REGION
ARG NEXT_PUBLIC_AWS_APPSYNC_AUTHENTICATION_TYPE
ARG NEXT_PUBLIC_AWS_APPSYNC_API_KEY
ARG NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID
ARG NEXT_PUBLIC_AWS_COGNITO_REGION

# Set as environment variables for the build
ENV NEXT_PUBLIC_AWS_PROJECT_REGION=$NEXT_PUBLIC_AWS_PROJECT_REGION
ENV NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT=$NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT
ENV NEXT_PUBLIC_AWS_APPSYNC_REGION=$NEXT_PUBLIC_AWS_APPSYNC_REGION
ENV NEXT_PUBLIC_AWS_APPSYNC_AUTHENTICATION_TYPE=$NEXT_PUBLIC_AWS_APPSYNC_AUTHENTICATION_TYPE
ENV NEXT_PUBLIC_AWS_APPSYNC_API_KEY=$NEXT_PUBLIC_AWS_APPSYNC_API_KEY
ENV NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID=$NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID
ENV NEXT_PUBLIC_AWS_COGNITO_REGION=$NEXT_PUBLIC_AWS_COGNITO_REGION

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22.14-alpine AS runner
WORKDIR /app

COPY --from=builder /app/.next/standalone ./

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["node", "server.js"]
