import type { Metadata } from "next";
import Header from "@/app/_components/header/Header";
import Footer from "@/app/_components/footer/Footer";
import "@/app/_styles/vars.css";
import "@/app/_styles/globals.css";

export const metadata: Metadata = {
  title: "VT Digital Library Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
